"""add unique constraint to items name

Revision ID: 6ecb1f29b02f
Revises: 3f4421feb2f9
Create Date: 2026-06-28 16:05:43.581316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ecb1f29b02f"
down_revision: Union[str, Sequence[str], None] = "3f4421feb2f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "items", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "items", type_="unique")
    # ### end Alembic commands ###
